apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miro-mcp-prod

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: production

images:
  - name: rg.fr-par.scw.cloud/fly-agile-prod/miro-mcp
    newTag: latest

patches:
  - target:
      kind: ConfigMap
      name: miro-mcp-config
    patch: |-
      - op: add
        path: /data/BASE_URI
        value: "https://mcp.fly-agile.com/mcp/miro"
  - target:
      kind: Deployment
      name: miro-mcp
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
