apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miro-mcp-dev

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

commonLabels:
  environment: development

images:
  - name: rg.fr-par.scw.cloud/fly-agile-prod/miro-mcp
    newTag: dev-latest
patches:
  - target:
      kind: ConfigMap
      name: miro-mcp-config
    patch: |-
      - op: add
        path: /data/BASE_URI
        value: "https://dev.mcp.fly-agile.com/mcp/miro"
